package db.FollowedArtists;

import javax.persistence.*;

import db.Users.User;

/**
 * Entity representing a followed artist within the application.
 */
@Entity
public class FollowedArtists {

    /**
     * Unique identifier for the user following the artist.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int user_id;
    
    /**
     * Spotify identifier for the artist.
     */
    private String spotify;

    /**
     * Serialized JSON containing artist-related items.
     */
    @Lob
    @Column
    private String items;

    /**
     * User entity associated with the followed artist.
     */
    @OneToOne
    private User user;

    /**
     * Constructs a new FollowedArtists instance.
     * 
     * @param user_id User identifier for whom the artists are followed.
     * @param spotify Spotify identifier for the artist.
     * @param items   Serialized JSON of items related to the artist.
     */
    public FollowedArtists(int user_id, String spotify, String items) {
        this.user_id = user_id;
        this.spotify = spotify;
        this.items = items;
    }

    /**
     * Default constructor for JPA.
     */
    public FollowedArtists() {
        // Default constructor used by JPA.
    }

    // Standard getters and setters for the entity fields.

    public int getUserID() {
        return this.user_id;
    }

    public void setUserID(int user_id) {
        this.user_id = user_id;
    }

    public String getSpotify() {
        return this.spotify;
    }

    public void setSpotify(String spotify) {
        this.spotify = spotify;
    }

    public String getItems() {
        return this.items;
    }

    public void setItems(String items) {
        this.items = items;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
