package db.RecentlyPlayed;

import javax.persistence.*;
import db.Users.User;

/**
 * Entity representing the recently played items for a user.
 */
@Entity
public class RecentlyPlayed {

    /**
     * Unique identifier for the user associated with the recently played items.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int user_id;
    
    /**
     * Spotify identifier for the user.
     */
    private String spotify;

    /**
     * Serialized JSON containing recently played items.
     */
    @Lob
    @Column
    private String items;

    /**
     * User entity associated with the recently played items.
     */
    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "user_id", referencedColumnName = "user_id")
    private User user;

    /**
     * Constructs a new RecentlyPlayed instance.
     * 
     * @param user_id User identifier for the recently played items.
     * @param spotify Spotify identifier for the user.
     * @param items   Serialized JSON of recently played items.
     * @param user    User entity associated with these recently played items.
     */
    public RecentlyPlayed(int user_id, String spotify, String items, User user) {
        this.user_id = user_id;
        this.spotify = spotify;
        this.items = items;
        this.user = user;
    }

    /**
     * Default constructor for JPA.
     */
    public RecentlyPlayed() {
        // Default constructor used by JPA.
    }

    // Standard getters and setters for the entity fields.

    public int getUserID() {
        return this.user_id;
    }

    public void setUserID(int user_id) {
        this.user_id = user_id;
    }

    public String getSpotify() {
        return this.spotify;
    }

    public void setSpotify(String spotify) {
        this.spotify = spotify;
    }

    public String getItems() {
        return this.items;
    }

    public void setItems(String items) {
        this.items = items;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
