package db.Users;

import javax.persistence.*;
import db.TopArtists.TopArtists;
import db.FollowedArtists.FollowedArtists;

/**
 * Entity class representing a user of the application.
 */
@Entity
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int user_id;
    private String spotify;
    private String display_name;
    private String picture_url;
    private String email;
    private String access_token;

    @OneToOne(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private FollowedArtists followed_artists;

    @OneToOne(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private TopArtists top_artists;

    /**
     * Constructor for creating a User with all properties.
     *
     * @param user_id       The ID of the user (generated by the database).
     * @param spotify       The Spotify ID of the user.
     * @param display_name  The display name of the user.
     * @param picture_url   The URL of the user's profile picture.
     * @param email         The email address of the user.
     * @param access_token  The access token for the user.
     */
    public User(int user_id, String spotify, String display_name, String picture_url, String email, String access_token) {
        this.user_id = user_id;
        this.spotify = spotify;
        this.display_name = display_name;
        this.picture_url = picture_url;
        this.email = email;
        this.access_token = access_token;
    }

    /**
     * Default constructor required for JPA.
     */
    public User() {
        // JPA requires a default constructor.
    }

    // Getters and Setters:

    public String getPictureURL() {
        return this.picture_url;
    }

    public void setPictureURL(String picture_url) {
        this.picture_url = picture_url;
    }

    public String getAccessToken() {
        return this.access_token;
    }

    public void setAccessToken(String access_token) {
        this.access_token = access_token;
    }

    public int getUserID() {
        return this.user_id;
    }

    public void setUserID(int user_id) {
        this.user_id = user_id;
    }

    public String getSpotify() {
        return this.spotify;
    }

    public void setSpotify(String spotify) {
        this.spotify = spotify;
    }

    public String getDisplayName() {
        return this.display_name;
    }

    public void setDisplayName(String display_name) {
        this.display_name = display_name;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
